# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

project_name: kubectl-kanvas-snapshot
version: 2
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.providerToken={{.Env.PROVIDER_TOKEN}}
      - -X main.mesheryCloudAPIBaseURL=https://cloud.layer5.io
      - -X main.mesheryAPIBaseURL=https://playground.meshery.io
      - -X main.workflowAccessToken={{.Env.GH_ACCESS_TOKEN}}
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    binary: kubectl-kanvas-snapshot

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - plugin.yaml
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  name_template: "kubectl-kanvas-snapshot {{.Tag}}"
  github:
    owner: meshery
    name: kubectl-kanvas-snapshot

# Extending the GoRelease to publish app manifest to scoop-bucket repository for Meshery
scoops: 
  # Template for the url which is determined by the given Token (github or gitlab)
  # Default for github is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  # Default for gitlab is "https://gitlab.com/<repo_owner>/<repo_name>/uploads/{{ .ArtifactUploadHash }}/{{ .ArtifactName }}"
  # Gitea is not supported yet, but the support coming
  # url_template: "http://github.mycompany.com/foo/bar/releases/{{ .Tag }}/{{ .ArtifactName }}"

  # Repository to push the app manifest to.
  - repository:
     owner: meshery
     name: scoop-bucket

  # Git author used to commit to the repository.
  # Defaults are shown.
    commit_author:
      name: mesheryctl releaser
      email: community@meshery.io

    # Your app's homepage.
    # Default is empty.
    homepage: "https://meshery.io"

    # Your app's description.
    # Default is empty.
    description: "The Cloud Native Management Plane."

    # Your app's license
    # Default is empty.
    license: Apache 2.0

    # Persist data between application updates
    # persist:
    # - "data"
    # - "config.toml"
