name: Kanvas Snapshot
on:
  workflow_dispatch:
    inputs:
      designID:
        description: 'The design ID to generate a snapshot for'
        required: false
        type: string
      assetLocation:
        description: 'Remote location where the generated asset (screenshot) will be stored'
        required: false
        type: string
      mesheryToken:
        description: 'Meshery authentication token (optional, uses service account token from secrets if not provided)'
        required: false
        type: string
      email:
        description: 'Email address to associate with the snapshot'
        required: false
        type: string

permissions: 
  actions: read
  contents: write
  security-events: write
  statuses: write
  pull-requests: write
  id-token: write

jobs:
  GenerateSnapshot:
    runs-on: ubuntu-latest
    outputs:
      snapshot_url: ${{ steps.generate_snapshot.outputs.resource_url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Environment
        run: |
          echo "MESHERY_URL=https://playground.meshery.io" >> $GITHUB_ENV
          echo "DESIGN_ID=${{ inputs.designID }}" >> $GITHUB_ENV
          echo "ASSET_LOCATION=${{ inputs.assetLocation }}" >> $GITHUB_ENV
          echo "MESHERY_TOKEN=${{ inputs.mesheryToken != '' && inputs.mesheryToken || secrets.MESHERY_TOKEN }}" >> $GITHUB_ENV
          
      - name: Verify Meshery Connection
        run: |
          curl -f -s -S -k -H "Cookie: token=${MESHERY_TOKEN};meshery-provider=Meshery" "${MESHERY_URL}/api/system/version" || echo "::warning::Meshery API not accessible"
          
      - uses: actions/checkout@v4
        with:
          path: action
          repository: layer5labs/kanvas-snapshot
          
      - id: generate_snapshot
        uses: layer5labs/kanvas-snapshot@v0.2.33
        env:
          CYPRESS_MESHERY_TOKEN: ${{ secrets.MESHERY_TOKEN }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mesheryToken: ${{ secrets.MESHERY_TOKEN }}
          application_type: "Design"
          skipComment: true
          designID: ${{ inputs.designID }}
          assetLocation: ${{ inputs.assetLocation }}
          email: ${{ inputs.email }}
            
      - name: Output Results
        run: |
          echo "Design ID: ${{ inputs.designID }}"
          echo "Asset Location: ${{ inputs.assetLocation }}"
          echo "Screenshot artifacts are available in the workflow artifacts section"