name: Kanvas Snapshot Generator
on:
  workflow_dispatch:
    inputs:
      designID:
        description: 'The design ID to generate a snapshot for'
        required: true

permissions: 
  actions: read
  contents: write
  security-events: write
  statuses: write
  pull-requests: write
  id-token: write

jobs:
  GenerateSnapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          path: action
          repository: layer5labs/kanvas-snapshot
      - id: test_result
        uses: layer5labs/kanvas-snapshot@v0.2.32
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mesheryToken: ${{ secrets.MESHERY_TOKEN }}
          designID: ${{ inputs.designID }}
          application_type: "Design"
          skipComment: true 